 const { cmd } = require('../command');

cmd({
    pattern: "makecmd",
    alias: ["cmdmaker", "gen-cmd"],
    desc: "Tengeneza kodi za command mpya kulingana na unavyotaka.",
    category: "owner",
    react: "🛠️",
    filename: __filename
}, async (conn, mek, m, { from, args, q, reply }) => {
    try {
        if (!q) return reply("*Mortal-Kombat-XR Command Maker* 🛠️\n\n*Matumizi:* `.makecmd jina:maelezo`\n\n*Mfano:* `.makecmd picha:itume picha ya simba kila mtu akiandika picha`\n\n> *Weka jina la command na kazi unayotaka ifanye baada ya nukta mbili.*");

        const data = q.split(':');
        if (data.length < 2) return reply("❌ Tafadhali tumia format hii -> `jina:kazi` (Mfano: `shabiki:nitumie picha ya yanga`) ");

        const cmdName = data[0].trim().toLowerCase();
        const cmdDesc = data[1].trim();

        reply(`*🛠️ M O R T A L - G E N E R A T O R*\n\n_Tengeneza command mpya kwa ajili ya:_ *${cmdName}*\n_Subiri kidogo..._ ⏳`);

        // Hapa bot inatengeneza kodi kulingana na template ya Mortal-Kombat-XR
        const generatedCode = `
/**
 * GENERATED BY MORTAL-KOMBAT-XR CMD MAKER
 * Command: ${cmdName}
 * Description: ${cmdDesc}
 */

const { cmd } = require('../command');

cmd({
    pattern: "${cmdName}",
    desc: "${cmdDesc}",
    category: "generated",
    react: "🔥",
    filename: __filename
}, async (conn, mek, m, { from, reply, q }) => {
    try {
        // Hapa unaweza kuongeza kodi zaidi kulingana na mahitaji yako
        return reply("*Mortal-Kombat-XR System:* Command ya ${cmdName} imetekelezwa kikamilifu! ✅");
    } catch (e) {
        console.log(e);
        reply("❌ Error occurred!");
    }
});`;

        // Bot itatuma kodi hiyo kama maandishi (Document au Text) ili mtumiaji acopy
        const finalMsg = `
*✅ C O M M A N D  R E A D Y !*

*Jina:* \`${cmdName}\`
*Kazi:* \`${cmdDesc}\`

*KODI YAKO HII HAPA (Copy na Paste):*
\`\`\`javascript
${generatedCode}
\`\`\`

> *Weka kodi hii kwenye folder la plugins kisha u-restart bot.*`;

        return reply(finalMsg);

    } catch (e) {
        console.error(e);
        reply("❌ System Crash wakati wa kutengeneza command.");
    }
});
