const { cmd } = require('../command');

cmd({
    pattern: "makecmd",
    alias: ["gen", "create"],
    desc: "Generates commands with different dynamic fancy styles.",
    category: "owner",
    react: "🎨",
    filename: __filename
}, async (conn, mek, m, { from, q, reply }) => {
    try {
        if (!q || !q.includes(':')) {
            return reply("*MK-XR DYNAMIC GEN* 🎨\n\n*Usage:* `.makecmd name:instruction` ");
        }

        let [name, ...descParts] = q.split(':');
        let cmdName = name.trim().toLowerCase().replace(/[^a-z0-9]/g, '');
        let cmdInstruction = descParts.join(':').trim().replace(/'/g, "\\'").replace(/`/g, "");

        // Hapa ndipo tunapozalisha kodi yenye urembo wa kubadilika-badilika (Dynamic)
        const generatedCode = `const { cmd } = require('../command');

cmd({
    pattern: "${cmdName}",
    desc: '${cmdInstruction}',
    category: "generated",
    react: "✨",
    filename: __filename
}, async (conn, mek, m, { from, pushName }) => {
    try {
        const date = new Date().toLocaleDateString();
        const time = new Date().toLocaleTimeString();
        const styles = [
            // STYLE 1: BOX STYLE
            \`╔════════════════════════╗\\n      ⚡ *MORTAL-KOMBAT-XR* ⚡\\n╚════════════════════════╝\\n👤 *User:* \${pushName}\\n📅 *Date:* \${date}\\n⌚ *Time:* \${time}\\n👑 *Owner:* Nyoni XMD\\n\\n*📍 Task:* ${cmdInstruction}\\n\\n> *Powered by Nyoni XMD Engine*\`,
            
            // STYLE 2: CLEAN LINE STYLE
            \`✨ *MK-XR DYNAMIC MENU* ✨\\n\\n*━━━━━━━━━━━━━━━━━━━━*\\n👤 *Hello:* \${pushName}\\n🕒 *Time:* \${time}\\n📂 *Command:* ${cmdName}\\n📝 *Info:* ${cmdInstruction}\\n*━━━━━━━━━━━━━━━━━━━━*\\n\\n> *Generated by MK-XR System*\`,
            
            // STYLE 3: SPARKLE STYLE
            \`🌟 ━━━ • ⚡ • ━━━ 🌟\\n  *NYONI XMD ENGINE*\\n🌟 ━━━ • ⚡ • ━━━ 🌟\\n\\n👤 *User:* \${pushName}\\n📅 *Date:* \${date}\\n🚀 *Action:* ${cmdInstruction}\\n\\n💎 *Enjoy the service!*\\n\\n> *Mortal Kombat System* \`
        ];

        // Hapa bot inachagua urembo mmoja kati ya hiyo mitatu kila inapopigwa command
        const randomStyle = styles[Math.floor(Math.random() * styles.length)];

        await conn.sendMessage(from, { 
            text: randomStyle,
            contextInfo: {
                externalAdReply: {
                    title: "𝙼𝙾𝚁𝚃𝙰𝙻-𝙺𝙾𝙼𝙱𝙰𝚃-𝚇𝚁 𝙳𝚈𝙽𝙰𝙼𝙸𝙲",
                    body: "Dynamic Fancy Menu",
                    thumbnailUrl: "https://telegra.ph/file/dcce2a3952975107ee010.jpg",
                    sourceUrl: "https://whatsapp.com/channel/0029VbAffhD2ZjChG9DX922r",
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        }, { quoted: mek });
    } catch (e) {
        console.error(e);
    }
});`;

        await conn.sendMessage(from, { 
            text: `*✅ DYNAMIC COMMAND GENERATED!*\n\n*Kila ukiitumia itabadilisha urembo (Style).* \n\n\`\`\`javascript\n${generatedCode}\n\`\`\`` 
        }, { quoted: mek });

    } catch (e) {
        reply("❌ Error generating dynamic code.");
    }
});
