const { cmd } = require('../command');

cmd({
    pattern: "makecmd",
    alias: ["gen", "createcmd"],
    desc: "Generates clean, crash-proof code for new plugins.",
    category: "owner",
    react: "🛠️",
    filename: __filename
}, async (conn, mek, m, { from, q, reply }) => {
    try {
        if (!q || !q.includes(':')) {
            return reply("*Mortal-Kombat-XR* 🛠️\n\n*Usage:* `.makecmd name:instruction` \n*Example:* `.makecmd news:Send the latest channel updates` ");
        }

        // Split name and instructions
        let [name, ...descParts] = q.split(':');
        let cmdName = name.trim().toLowerCase().replace(/[^a-z0-9]/g, '');
        let cmdInstruction = descParts.join(':').trim();

        // Using Backticks (`) inside the template to prevent quote conflicts
        const generatedCode = `const { cmd } = require('../command');

cmd({
    pattern: "${cmdName}",
    desc: \`${cmdInstruction}\`,
    category: "generated",
    react: "✅",
    filename: __filename
}, async (conn, mek, m, { from, reply }) => {
    try {
        // Automatically generated by MK-XR Command Maker
        const responseText = \`*MORTAL-KOMBAT-XR SYSTEM*\\n\\n*Command:* ${cmdName}\\n*Task:* ${cmdInstruction}\`;
        
        await conn.sendMessage(from, { text: responseText }, { quoted: mek });
    } catch (e) {
        console.error(e);
    }
});`;

        // Sending the code as a clean text block
        await conn.sendMessage(from, { 
            text: `*✅ COMMAND CODE GENERATED!*\n\n*Name:* \`${cmdName}\` \n\n\`\`\`javascript\n${generatedCode}\n\`\`\`\n\n> *Copy the code above, create a new .js file in your plugins folder, paste it, and restart.*` 
        }, { quoted: mek });

    } catch (e) {
        console.error(e);
        reply("❌ Error generating code. Please check your syntax.");
    }
});
