const { cmd, commands } = require('../command');

cmd({
    pattern: "menu1",
    react: "🙃",
    category: "generated",
    desc: "Auto-generated by Nyoni Maker",
    filename: __filename
}, async (conn, mek, m, { from, pushName, reply }) => {
    try {
        
    const listBody = `┏━━━━━━━「 *MENU* 」━━━━━━━┓
┃
┃ 👤 *Hello:* ${pushName}
┃ 📞 *Contact:* 255763111390
┃ 🤖 *Core:* Nyoni
┃
*───「 COMMANDS 」───*
┃ ${index + 1}. 🔥 *MENU*\n┃ ${index + 1}. 🔥 *PING*\n┃ ${index + 1}. 🔥 *ALIVE*\n┃ ${index + 1}. 🔥 *REPO*\n┃ ${index + 1}. 🔥 *NYONI*\n
┃
┗━━━━━━━━━━━━━━━━━━━━┛`;
    await conn.sendMessage(from, { text: listBody }, { quoted: mek });
        
        // Ad-Reply Footer (Image Card)
        await conn.sendMessage(from, { 
            contextInfo: {
                externalAdReply: {
                    title: "Nyoni",
                    body: "Created by Nyonixmd",
                    thumbnailUrl: " https://files.catbox.moe/folixt.jpg",
                    sourceUrl: "https://whatsapp.com/channel/0029VbAffhD2ZjChG9DX922r",
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        });
    } catch (e) { 
        console.log(e);
        reply("❌ Error occurred!");
    }
});
