const { cmd, commands } = require('../command');

cmd({
    pattern: "menu1",
    react: "🙃",
    category: "generated",
    desc: "Auto-generated by Nyoni Maker",
    filename: __filename
}, async (conn, mek, m, { from, pushName, reply }) => {
    try {
        
    const listBody = `┏━━━━━━━「 *MENU* 」━━━━━━━┓
┃
┃ 👤 *Hello:* ${pushName}
┃ 📞 *Contact:* 255763111390
┃ 🤖 *Core:* Nyoni
┃
*───「 COMMANDS 」───*
┃ ${index + 1}. 🔥 *╭─⊷🐉𝐌𝐀𝐈𝐍-𝐂𝐌𝐃─
│ ⌬ ─· MENU                    
│ ⌬ ─· PING
│ ⌬ ─· PING2
│ ⌬ ─· UPTIME 
│ ⌬ ─· S
│ ⌬ ─· BOTINFO
│ ⌬ ─· LISTPLUGIN 
│ ⌬ ─· UPDATE 
│ ⌬ ─· REQUEST 
╰────────────
╭─⊷✅𝐂𝐓𝐑𝐋-𝐁𝐎𝐓─
│ ⌬ ─· PUBLIC                    
│ ⌬ ─· PRIVATE
│ ⌬ ─· ADDACCESS
│ ⌬ ─· DELACCESS    
│ ⌬ ─· AUTOREACT    
│ ⌬ ─· BLOCK
│ ⌬ ─· AUTOTYPING
│ ⌬ ─· AUTORECORD 
│ ⌬ ─· AUTOBIO
│ ⌬ ─· SETPREFIX 
│ ⌬ ─· AUTOSTATUSVIEW 
│ ⌬ ─· ONLYGC
│ ⌬ ─· ONLYPC
│ ⌬ ─· UNAVAILABLE 
│ ⌬ ─· >
│ ⌬ ─· $
╰────────────
╭─⊷📁𝐌𝐄𝐃𝐈𝐀-𝐂𝐌𝐃─
│ ⌬ ─· PLAY       
│ ⌬ ─· PLAYDOC       
│ ⌬ ─· YTMP4 
│ ⌬ ─· YTVID 
│ ⌬ ─· YTS 
│ ⌬ ─· PINTERESTDL 
│ ⌬ ─· VV
│ ⌬ ─· SONG
│ ⌬ ─· TWITTERDL
│ ⌬ ─· TT
│ ⌬ ─· TIKTOK  
│ ⌬ ─· IGDL      
│ ⌬ ─· YTMP3    
│ ⌬ ─· VIDEO
╰────────────

╭─⊷🤖AI-CMD─
│ ⌬ ─· GEMMA 
│ ⌬ ─· COPILOT       
╰────────────
╭─⊷⚡𝐆𝐄𝐓-𝐂𝐌𝐃─
│ ⌬ ─· GETHTML
│ ⌬ ─· GETPP 
│ ⌬ ─· GETPLUGIN 
│ ⌬ ─· SAVE
│ ⌬ ─· GITCLONE
│ ⌬ ─· WEATHER 
│ ⌬ ─· SHORTURL
╰────────────
╭─⊷👥𝐆𝐑𝐔𝐏-𝐂𝐌𝐃─
│ ⌬ ─· ADD
│ ⌬ ─· REMOVE
│ ⌬ ─· PROMOTE
│ ⌬ ─· REVOKE
│ ⌬ ─· APPROVE
│ ⌬ ─· REJECT
│ ⌬ ─· ANTILINKGC
│ ⌬ ─· ANTILINK
│ ⌬ ─· TAGALL
│ ⌬ ─· HIDETAG
│ ⌬ ─· CLOSE
│ ⌬ ─· OPEN
│ ⌬ ─· KICKALL
│ ⌬ ─· LINKGC
│ ⌬ ─· SETPPGC
│ ⌬ ─· SETDESC
│ ⌬ ─· TAGME
│ ⌬ ─· WARN
│ ⌬ ─· UNWARN
│ ⌬ ─· WELCOME 
│ ⌬ ─· GOODBYE 
│ ⌬ ─· DISP-1
│ ⌬ ─· DISP-7 
│ ⌬ ─· DISP-90 
│ ⌬ ─· DISP-OFF
╰────────────
╭─⊷⚓𝐓𝐎𝐎𝐋-𝐂𝐌𝐃─
│ ⌬ ─· ENC
│ ⌬ ─· IDCH 
│ ⌬ ─· DEV
╰────────────
╭─⊷🐥𝐄𝐏𝐇𝐎𝐓𝐎-𝐂𝐌𝐃─
│ ⌬ ─· GLITHTEXT
│ ⌬ ─· LIGHTEFFECTS 
│ ⌬ ─· WRITETEXT
│ ⌬ ─· ADVANCEDGLOW
│ ⌬ ─· TYPOGRAPHYTEXT
│ ⌬ ─· PIXELGLITCH
│ ⌬ ─· NEONGLITCH 
│ ⌬ ─· FLAGTEXT
│ ⌬ ─· FLAG3DTEXT
│ ⌬ ─· DELETINGTEXT
│ ⌬ ─· BLACKPINKSTYLE
│ ⌬ ─· GLOWINGTEX
│ ⌬ ─· UNDERWATER 
│ ⌬ ─· LOGOMAKER
│ ⌬ ─· CARTOONSTYLE
│ ⌬ ─· PAPERCUTSTYLE
│ ⌬ ─· WATERCOLORTEXT
│ ⌬ ─· EFFECTCLOUDS
│ ⌬ ─· BLACKPINKLOGO
│ ⌬ ─· GRADIENTTEXT
│ ⌬ ─· LUXURYGOLD
│ ⌬ ─· SANDSUMMER
│ ⌬ ─· MULTICOLOREDNEON
│ ⌬ ─· GALAXYWALLPAPER 
│ ⌬ ─· 1917STYLE
│ ⌬ ─· GALAXYSTYLE
│ ⌬ ─· ROYALTEXT
│ ⌬ ─· FREECREATE
╰────────────
╭─⊷🦞𝐅𝐔𝐍-𝐂𝐌𝐃─
│ ⌬ ─· TRUTH
│ ⌬ ─· DARE  
│ ⌬ ─· CRY
│ ⌬ ─· KILL
│ ⌬ ─· HAPPY
│ ⌬ ─· HUG
│ ⌬ ─· LICK
│ ⌬ ─· PAT
│ ⌬ ─· BITE
│ ⌬ ─· KISS
│ ⌬ ─· BULLY
│ ⌬ ─· BONK
│ ⌬ ─· POKE
│ ⌬ ─· SLAP
│ ⌬ ─· WINK
│ ⌬ ─· DANCE
│ ⌬ ─· CUDDLE
│ ⌬ ─· CRINGE
│ ⌬ ─· BLUSH
│ ⌬ ─· SMILE
│ ⌬ ─· SHINOBU
│ ⌬ ─· HANDHOLD
│ ⌬ ─· HIGHFIVE
│ ⌬ ─· WAVE
│ ⌬ ─· NOM
│ ⌬ ─· FEED
│ ⌬ ─· MEOW
│ ⌬ ─· WOOF
│ ⌬ ─· LIZARD
│ ⌬ ─· SPANK
│ ⌬ ─· TICKLE
│ ⌬ ─· FOX_GIRL
│ ⌬ ─· AVATAR
│ ⌬ ─· GOOSE
│ ⌬ ─· 8BALL
│ ⌬ ─· GECG
╰────────────
╭─⊷🔐𝐅𝐎𝐎𝐓𝐁𝐀𝐋𝐋-𝐂𝐌𝐃─
│ ⌬ ─· EPL
│ ⌬ ─· LALIGA
│ ⌬ ─· SERIE-A
│ ⌬ ─· LIGUE-1
│ ⌬ ─· BUNDESLIGA
╰────────────
> BY REDDRAGON TECH*\n
┃
┗━━━━━━━━━━━━━━━━━━━━┛`;
    await conn.sendMessage(from, { text: listBody }, { quoted: mek });
        
        // Ad-Reply Footer (Image Card)
        await conn.sendMessage(from, { 
            contextInfo: {
                externalAdReply: {
                    title: "Nyoni",
                    body: "Created by Nyonixmd",
                    thumbnailUrl: " https://files.catbox.moe/folixt.jpg",
                    sourceUrl: "https://whatsapp.com/channel/0029VbAffhD2ZjChG9DX922r",
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        });
    } catch (e) { 
        console.log(e);
        reply("❌ Error occurred!");
    }
});
