
const { cmd } = require('../command');

cmd({
    pattern: "ping4",
    desc: 'hapa ndipo utaona speed ya bot',
    category: "generated",
    react: "✨",
    filename: __filename
}, async (conn, mek, m, { from, pushName }) => {
    try {
        const date = new Date().toLocaleDateString();
        const time = new Date().toLocaleTimeString();
        const styles = [
            // STYLE 1: BOX STYLE
            `╔════════════════════════╗\n      ⚡ *MORTAL-KOMBAT-XR* ⚡\n╚════════════════════════╝\n👤 *User:* ${pushName}\n📅 *Date:* ${date}\n⌚ *Time:* ${time}\n👑 *Owner:* Nyoni XMD\n\n*📍 Task:* hapa ndipo utaona speed ya bot\n\n> *Powered by Nyoni XMD Engine*`,
            
            // STYLE 2: CLEAN LINE STYLE
            `✨ *MK-XR DYNAMIC MENU* ✨\n\n*━━━━━━━━━━━━━━━━━━━━*\n👤 *Hello:* ${pushName}\n🕒 *Time:* ${time}\n📂 *Command:* ping4\n📝 *Info:* hapa ndipo utaona speed ya bot\n*━━━━━━━━━━━━━━━━━━━━*\n\n> *Generated by MK-XR System*`,
            
            // STYLE 3: SPARKLE STYLE
            `🌟 ━━━ • ⚡ • ━━━ 🌟\n  *NYONI XMD ENGINE*\n🌟 ━━━ • ⚡ • ━━━ 🌟\n\n👤 *User:* ${pushName}\n📅 *Date:* ${date}\n🚀 *Action:* hapa ndipo utaona speed ya bot\n\n💎 *Enjoy the service!*\n\n> *Mortal Kombat System* `
        ];

        // Hapa bot inachagua urembo mmoja kati ya hiyo mitatu kila inapopigwa command
        const randomStyle = styles[Math.floor(Math.random() * styles.length)];

        await conn.sendMessage(from, { 
            text: randomStyle,
            contextInfo: {
                externalAdReply: {
                    title: "𝙼𝙾𝚁𝚃𝙰𝙻-𝙺𝙾𝙼𝙱𝙰𝚃-𝚇𝚁 𝙳𝚈𝙽𝙰𝙼𝙸𝙲",
                    body: "Dynamic Fancy Menu",
                    thumbnailUrl: "https://telegra.ph/file/dcce2a3952975107ee010.jpg",
                    sourceUrl: "https://whatsapp.com/channel/0029VbAffhD2ZjChG9DX922r",
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        }, { quoted: mek });
    } catch (e) {
        console.error(e);
    }
});
