const { cmd } = require('../command');
const { exec } = require('child_process');
const fs = require('fs');
const path = require('path');

cmd({
    pattern: "videomake",
    desc: "Create video from text",
    category: "video",
    react: "🎬",
    filename: __filename
}, async (conn, mek, m, { from, text, reply }) => {
    try {
        if (!text) return reply("*Example:* .videomake HELLO WORLD");

        // Angalia kama FFmpeg ipo
        exec('ffmpeg -version', async (err) => {
            if (err) return reply("❌ **FFmpeg is STILL not installed!**\nRun: `pkg install ffmpeg` first.");

            await reply("🎬 *Creating video, please wait...*");
            
            const videoPath = path.join(__dirname, `../temp_${Date.now()}.mp4`);
            const safeText = text.replace(/['"]/g, "");

            // Amri rahisi ya FFmpeg inayofanya kazi popote
            const command = `ffmpeg -f lavfi -i color=c=blue:s=640x480:d=5 -vf "drawtext=text='${safeText}':fontcolor=white:fontsize=40:x=(w-text_w)/2:y=(h-text_h)/2" -c:v libx264 -pix_fmt yuv420p -y "${videoPath}"`;

            exec(command, async (error) => {
                if (error) return reply("❌ Video Error: " + error.message);

                await conn.sendMessage(from, { video: { url: videoPath }, caption: "✅ Generated by RAHEEM-XMD" }, { quoted: mek });
                
                // Futa file
                if (fs.existsSync(videoPath)) fs.unlinkSync(videoPath);
            });
        });
    } catch (e) {
        reply("❌ Error: " + e.message);
    }
});
